### ISSUE TITLE
Source of your data?

### ISSUE THREAD

**Issue by k00ni** [juliuste/lvb#12]
Hi, which data source do you use? Do you check for updates and merge them?

**Comment by juliuste** [comment]
Sorry for the very late response, if you're still interested in an answer: This package is something between an API client and a scraper, it uses API calls made by the LVB website. I didn't have much time to maintain the package, but @hashworks has kindly provided some updates to the calls, to that everything works (still/again) as of now.

**Comment by juliuste** [comment]
Please re-open if necessary.
