### ISSUE TITLE
stations(query, [opt]) not returning a station object for a valid station

### ISSUE THREAD

**Issue by raywo** [juliuste/lvb#2]
Querying the api with the station names "Klingerweg" or "Nonnenstraße" returns an empty array. Both names are valid station names according to the easy.GO app.

Is this a bug in your package or a problem with the LVB api?

**Comment by JervisTetch** [comment]
That's a problem with the LVB api. You can easily have a look here by yourself: https://www.l.de/verkehrsbetriebe/fahrplan/

If you have a look on 'Haltestelle' you can see which stations are included. The Klingerweg is indeed completely missing but Nonnenstraße is simply stored as 'Nonnenstr.' so querrying this returns valid results.

**Comment by raywo** [comment]
Oh. I see. The data provided by the LVB api is indeed less than perfect. Thank you for answer.
