### ISSUE TITLE
Stations which are also stops for local or long distance trains have no stationID.

### ISSUE THREAD

**Issue by raywo** [juliuste/lvb#3]
Stations like “Hauptbahnhof“ or “Wahren“ can be queried and are found by a *stations* query but the ``id`` is ``null``. Therefore these stations can’t be used in a *departures* query since they also return multiple results when a *stations* query is used.

Is there another way to get departures for those stations?

**Comment by juliuste** [comment]
I will have a look at this in the next couple of days (sorry for the long reaction time).

**Comment by juliuste** [comment]
Just realized this has been unanswered since more than 2 years, really sorry about that 😄. Please re-open if you're still interested in an answer.
